---
name: Checks

on: [push]

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:
          - name: Print Docker Login Command
            run: echo "docker login -u ${{ secrets.DOCKERHUB_USER }} -p ***masked***" && echo "docker login -u ${{ secrets.DOCKERHUB_USER }} -p ***masked***"
            shell: /usr/bin/bash -e {0}
          - name: Login to DockerHub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Checkout
            uses: actions/checkout@v2
          - name: Test
            run : docker-compose run --rm app sh -c "python manage.py test"
          - name: Lint
            run : docker-compose run --rm app sh -c "flake8"